// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msgfiles/msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringMsgResp struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMsgResp) Reset()         { *m = StringMsgResp{} }
func (m *StringMsgResp) String() string { return proto.CompactTextString(m) }
func (*StringMsgResp) ProtoMessage()    {}
func (*StringMsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c99a4a80dfa99c0, []int{0}
}

func (m *StringMsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMsgResp.Unmarshal(m, b)
}
func (m *StringMsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMsgResp.Marshal(b, m, deterministic)
}
func (m *StringMsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMsgResp.Merge(m, src)
}
func (m *StringMsgResp) XXX_Size() int {
	return xxx_messageInfo_StringMsgResp.Size(m)
}
func (m *StringMsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_StringMsgResp proto.InternalMessageInfo

func (m *StringMsgResp) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *StringMsgResp) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type StringMsgReq struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMsgReq) Reset()         { *m = StringMsgReq{} }
func (m *StringMsgReq) String() string { return proto.CompactTextString(m) }
func (*StringMsgReq) ProtoMessage()    {}
func (*StringMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c99a4a80dfa99c0, []int{1}
}

func (m *StringMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMsgReq.Unmarshal(m, b)
}
func (m *StringMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMsgReq.Marshal(b, m, deterministic)
}
func (m *StringMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMsgReq.Merge(m, src)
}
func (m *StringMsgReq) XXX_Size() int {
	return xxx_messageInfo_StringMsgReq.Size(m)
}
func (m *StringMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_StringMsgReq proto.InternalMessageInfo

func (m *StringMsgReq) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func init() {
	proto.RegisterType((*StringMsgResp)(nil), "msg.StringMsgResp")
	proto.RegisterType((*StringMsgReq)(nil), "msg.StringMsgReq")
}

func init() { proto.RegisterFile("msgfiles/msg.proto", fileDescriptor_9c99a4a80dfa99c0) }

var fileDescriptor_9c99a4a80dfa99c0 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0x2d, 0x4e, 0x4f,
	0xcb, 0xcc, 0x49, 0x2d, 0xd6, 0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xce, 0x2d, 0x4e, 0x57, 0xd2, 0xe7, 0xe2, 0x0d, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0xf7, 0x2d, 0x4e,
	0x0f, 0x4a, 0x2d, 0x2e, 0x10, 0xe2, 0xe1, 0x62, 0x2c, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x62, 0x2c, 0x16, 0x12, 0xe0, 0x62, 0x4e, 0x2d, 0x2a, 0x92, 0x60, 0x02, 0xf3, 0x41, 0x4c, 0x25,
	0x19, 0x2e, 0x1e, 0x24, 0x0d, 0x85, 0xa8, 0xea, 0x9d, 0xf8, 0xb9, 0xd8, 0x8a, 0x8a, 0xf5, 0x72,
	0x8b, 0xd3, 0x3d, 0x98, 0xa3, 0x40, 0xe6, 0x27, 0xb1, 0x81, 0xed, 0x32, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x7d, 0x2b, 0xe9, 0x3a, 0x81, 0x00, 0x00, 0x00,
}
